# Generated by Django 4.1 on 2022-08-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('Hash', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Cert_Hash')),
                ('Data', models.TextField(verbose_name='Cert_Data')),
            ],
        ),
    ]
